In [ ]:
import mysql.connector
import datetime 
from datetime import datetime

now = datetime.now()

class rest():
    def __init__ (self,hostname,username,password,database):
        self.hostname=hostname
        self.username=username
        self.password=password
        self.database=database
    
    def connect(self):
        print("*"*50)
        print(" "*15,end='')
        print("Hotel Details")
        print("*"*50)
        
        db=mysql.connector.connect(host=self.hostname,username=self.username,password=self.password,database=self.database)
        print("connection succesful")
        
        query='create table if not exists restaurant(s_no int auto_increment not null primary key,o_no int,o_amount int, o_date timestamp default now())'
        my_pointer=db.cursor()
        my_pointer.execute(query)
        
        query='create table if not exists inventory(item_id int not null primary key,item_name varchar(50),entry_date timestamp default now())'
        my_pointer=db.cursor()
        my_pointer.execute(query)
        
        print("created")

        while True:
            choice=int(input('1->Restaurant\n2->Inventory\n3->Exit\n Enter your choice'))
            
             #Reataurant table
                
            if choice==1:
                s_no=input("enter serial no.")
                o_no=input("enter order no")
                o_amount=input("enter order amount")
                o_date = now.strftime('%Y-%m-%d %H:%M:%S')  
                sql="insert into restaurant values({},{},{},'{}')".format(s_no,o_no,o_amount,o_date)
                my_pointer=db.cursor()
                my_pointer.execute(sql)
                p=my_pointer.fetchall()
                for i in p:
                    print(i)
                print("Restaurant table created successfully")
                db.commit()
                
                a=input('Do you want to enter more records in restaurant? (Y/ N)')
                if a!='n':
                    continue
                else:
                    break
                
                try:
                    db = mysql.connector.connect(user='localhost', database='python',password='amruta95')
                    my_pointer=db.cursor()
                    my_pointer.execute("SELECT * FORM  restaurant")   # Syntax error in query
                    db.close()
                except Exception as err:
                    print("Something went wrong: {}".format(err))

              
                #Inventory table
                
            if choice ==2:
                item_id=input("enter item id")
                item_name=input("enter the item name: ")
                entry_date = now.strftime('%Y-%m-%d %H:%M:%S')
                sql="insert into inventory values({},'{}','{}')".format( item_id,item_name,entry_date)
                my_pointer=db.cursor()
                my_pointer.execute(sql)
                p=my_pointer.fetchall()
                for i in p:
                    print(i)
                print("Inventory table created successfully")
                db.commit()  
                
                a=input('Do you want to center more records in inventory table(Y/N)')
                if a!='n':
                    continue
                else:
                    break
                    
            try:
                db = mysql.connector.connect(user='root', database='python',password='amruta95')
                my_pointer=db.cursor()
                my_pointer.execute("SELECT * FORM inventory")   # Syntax error in query
                db.close()
            except Exception as err:
                print("Something went wrong: {}".format(err))
                
                
            if choice ==3:
                break    
       
r= rest('localhost','root','amruta95','python')
r.connect()

**************************************************
               Hotel Details
**************************************************
connection succesful
created